services:
  neuroai:
    build:
      context: .
      dockerfile: Containerfile
    container_name: neuroai
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - CONTAINER=true
    ports:
      - "8888:8888"
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: pipenv run jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]